defaults:
  -
    scope:
      path: "fjs/en"
    values:
      otherlang: "In other languages:"
      anyquestions: "If you have any questions, you are encourage to contact the author at"
  -
    scope:
      path: "fjs"
    values:
      layout: "fjs"
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "misotanni"
