plugins:
  - jekyll-redirect-from
defaults:
  -
    scope:
      path: "fjs/en"
    values:
      otherlang: "English · In other languages:"
      credits: "Credits and contact"
      disclaimer: "" # no disclaimer to be had
  -
    scope:
      path: "fjs/pl"
    values:
      otherlang: "Polski · W innych językach:"
      credits: "Autorzy, kontakt"
      disclaimer: "Tłumaczenie może nie być aktualne z główną wersją angielską."
  -
    scope:
      path: "fjs/jbo"
    values:
      otherlang: "jbobau .i bau lo drata zo'u:"
      credits: "lo finti datni jo'u lo jikca judri"
      disclaimer: ".i cumki fa lo nu lo xe fanva na sarxe lo pe ca ralju ke glibau versiio"
  -
    scope:
      path: "fjs/fr"
    values:
      otherlang: "Français · En d'autres langues:"
      credits: "À la page des crédits et du contact"
      disclaimer: "Il peut être que la traduction n'est pas à jour avec la version anglaise principale."
  -
    scope:
      path: "fjs/de"
    values:
      otherlang: "Deutsch · In anderen Sprachen:"
      credits: "Zur Credits- und Kontaktseite"
      disclaimer: "Die Übersetzung kann mit der englischer Hauptfassung nicht aktuell sein."
  -
    scope:
      path: "fjs"
    values:
      layout: "fjs"
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "misotanni"
