defaults:
  -
    scope:
      path: "fjs/en"
    values:
      otherlang: "In other languages:"
  -
    scope:
      path: "fjs"
    values:
      layout: "fjs"
  -
    scope:
      path: ""
    values:
      layout: "default"
